### ISSUE TITLE
Running hello_flask.py with python3 gives error "ImportError: No module named 'flask'"

### ISSUE THREAD

**Issue by jgriffith23** [clintgibler/webapp_security_by_example#3]
Full error text, for reference:

```
(env) Jennifers-MacBook-Pro-2:hello_flask jennifer$ python3 hello_flask.py 
Traceback (most recent call last):
  File "hello_flask.py", line 1, in <module>
    from flask import Flask
ImportError: No module named 'flask'
```

Odd, because requirements.txt clearly has Flask==0.11.1. May need to specify `pip3` install?

File runs fine with the `python` command, though.

**Comment by clintgibler** [comment]
Thanks for the heads up! You're exactly right, the README was advising people to use `pip` but then `python3`. I've updated the README to make this more clear (that people should use `pip` and `python` or `pip3` and `python3`). 

Please let me know if there's anything that could be more clear, thanks!
